# Generated by Django 5.0.4 on 2024-05-26 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0004_alter_customer_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstaMierdaNoAnda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
