# Generated by Django 5.0.4 on 2024-05-26 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0005_estamierdanoanda'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EstaMierdaNoAnda',
        ),
    ]
