# Generated by Django 5.0.4 on 2024-12-21 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0009_alter_orderline_vat_type_alter_product_vat_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderline',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orderline',
            name='vat_type',
            field=models.CharField(choices=[('standard', '21%'), ('reduced', '10,5%'), ('zero', 'Sin IVA')], default='standard', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='vat_type',
            field=models.CharField(choices=[('standard', '21%'), ('reduced', '10,5%'), ('zero', 'Sin IVA')], default='standard', max_length=100),
        ),
    ]
